---
collections:
  - name: amazon.aws
  - name: hetzner.hcloud
  - name: ansible.posix
    source: https://galaxy.ansible.com
    version: ">=2.1.0"

roles:
  - name: andreswebs.dev_box
  - name: andreswebs.docker
