---
plugin: amazon.aws.aws_ec2

profile: "{{ lookup('env', 'AWS_PROFILE') | default('default', true) }}"

regions:
  - us-east-1

keyed_groups:
  - key: tags["Name"]
    prefix: vm_tag

filters:
  instance-state-name: running

use_contrib_script_compatible_ec2_tag_keys: true

hostnames:
  - instance-id
